import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import PrimaryLinkButton from "~/components/PrimaryLinkButton";

function HeroBanner() {
  return (
    <section className="mb-24 mt-12 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-4">
        <h1 className="text-6xl">Generate icons with a click of a button</h1>
        <p className="text-2xl">
          Use AI to generate icons in seconds instead of paying a designer and
          waiting for them to create them for you.
        </p>
        <PrimaryLinkButton href="/generate" className="self-start">
          Generate your Icons
        </PrimaryLinkButton>
      </div>
      <Image
        className="order-first sm:-order-none"
        src="/banner.jpeg"
        alt="an image of a bunch of icons"
        width={600}
        height={394}
      />
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
